<?php

namespace PaBundle\Repository;

/**
 * LigneJsonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigneJsonRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLignes( $date )
	{
		$db = $this->_em->getConnection();

        if( ($date!=null) || (!empty($date)) )
	        $query = "SELECT DISTINCT(date), ligne  FROM questionnaire_s WHERE valid=2 AND `generated`=0 
						AND date='$date' ";
        else $query = "SELECT DISTINCT(date), ligne FROM questionnaire_s WHERE valid=2 AND `generated`=0 ";
	
		$stmt = $db->prepare($query);
		$stmt->execute();
		$result = $stmt->fetchAll();
	
		return $result;
	}

   public function listIdByLineDate( $ligne, $date )
	{
		$db = $this->_em->getConnection();

        $query = "SELECT id_global FROM questionnaire_s WHERE valid=2 
					AND `generated`=0 AND ligne='$ligne' 
					AND date='$date' ORDER BY heure ";
	
		$stmt = $db->prepare($query);
		$stmt->execute();
		$result = $stmt->fetchAll();
	
		return $result;
	}

	public function getInfosLigne( $ligne )
	{
		$db = $this->_em->getConnection();

        $query = "SELECT id_global as id, zone, ligne, date, 'generated' as json 
					FROM questionnaire_s WHERE ligne='$ligne' GROUP BY zone, date ";
	
		$stmt = $db->prepare($query);
		$stmt->execute();
		$result = $stmt->fetchAll();
	
		return $result;
	}
	
	public function updateValue( $zone, $value, $date )
	{
		$db = $this->_em->getConnection();

		$date = str_replace('_', '/', $date);

        $query = "UPDATE questionnaire_s SET `generated`=$value WHERE zone='$zone' AND date='$date'";
	
		$stmt = $db->prepare($query);
		$stmt->execute();

	}
}
