<?php

namespace PaBundle\Repository;

/**
 * QuestionnaireSRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionnaireSRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAll()
	{
		$qb = $this->createQueryBuilder('q');
		$qb->select('q')->addOrderBy($qb->expr()->substring('q.date', 1, 2), 'desc');
						
		return $qb->getQuery()->getResult();
		}
	
	public function getByFilter( $typeFilter, $dataFilter )
	{
		$db = $this->_em->getConnection();

		$qb = $this->createQueryBuilder('q');

		if( $typeFilter == "enqueteur" )
		{
			$qb
				->select('q')
				->where('q.enqueteur = :numEnqueteur')
				->orderBy('q.date', 'desc')
				->setParameter('numEnqueteur', $dataFilter);
		}

		else if( $typeFilter == "ligne" )
		{
			$qb
				->select('q')
				->where('q.ligne = :ligne')
				->orderBy('q.date', 'desc')
				->setParameter('ligne', $dataFilter);
		}

		else if( $typeFilter == "zone" )
		{
			$qb
				->select('q')
				->where('q.zone = :zone')
				->orderBy('q.date', 'desc')
				->setParameter('zone', $dataFilter);
		}

		else if( $typeFilter == "date" )
		{
			$qb
				->select('q')
				->where('q.date = :date')
				->orderBy('q.date', 'desc')
				->setParameter('date', $dataFilter);
		}

		else if( $typeFilter == "gipa" )
		{
			$qb
				->select('q')
				->where('q.gipa = :gipa')
				->orderBy('q.gipa', 'desc')
				->setParameter('gipa', $dataFilter);
		}


		return $qb->getQuery()->getResult();
	}

	public function listItems( $item, $table )
	{
		$db = $this->_em->getConnection();

		$query = "SELECT DISTINCT( $item ) as  $item FROM $table";
		$stmt = $db->prepare( $query );
		$stmt->execute();
		$result = $stmt->fetchAll();

		return $result;
	}

	public function getAll( )
	{
		$qb = $this->createQueryBuilder('q');
		$qb->select('q')->addOrderBy( 'substring(q.date,0,2)', 'desc' )
						->addOrderBy( 'substring(q.date,4,2)', 'desc' );
		return $qb->getQuery()->getResult();
	}

	public function listPhotosByMesure( $id )
	{
		$db = $this->_em->getConnection();

		$query = "SELECT * FROM photo WHERE id_global=$id";
		$stmt = $db->prepare( $query );
		$stmt->execute();
		$result = $stmt->fetchAll();

		return $result;
	}
	public function historyListPhotosByMesure( $id, $table )
	{
		$db = $this->_em->getConnection();

		$query = "SELECT * FROM photo_".$table." WHERE id_global=$id";
		$stmt = $db->prepare( $query );
		$stmt->execute();
		$result = $stmt->fetchAll();

		return $result;
	}

	public function getTitlePhotoByName( $id, $name )
	{
		$db = $this->_em->getConnection();

		$query = "SELECT titre FROM photo WHERE id_global=$id AND name='$name'";
		$stmt = $db->prepare( $query );
		$stmt->execute();
		$result = $stmt->fetchAll();

		return $result;
	}

	public function savePhoto( $id, $datas )
	{
		$db = $this->_em->getConnection();

		$result=false;
		for($i=0; $i<sizeof( $datas ); $i++)
        {
            $query = "INSERT INTO photo ( id_global, name, titre, date ) 
						VALUES ( $id, '".$datas[$i]['name']."', '".$datas[$i]['title']."', NOW())
						on duplicate key update id_global=$id,
        				name='".$datas[$i]['name']."', titre='".$datas[$i]['title']."', date=NOW()";
			$stmt = $db->prepare( $query );
			$result = $stmt->execute();
			
        }
		return $result;
	}

	public function removePhoto( $id, $name )
	{
		$db = $this->_em->getConnection();

		$query = "DELETE FROM photo WHERE id_global=$id AND name='$name'";
		$stmt = $db->prepare( $query );
		$rs = $stmt->execute();

		return $rs;
	}

	public function insertDatas( $list_lignes )
	{
		for($p=0; $p<sizeof($list_lignes[0]); $p++)
		{
			iconv( "Windows-1252", "UTF-8", $list_lignes[0][$p] );
		}

		$db = $this->_em->getConnection();
		
		try {
		
			$db->beginTransaction();
		
		
			if( $list_lignes[0][0] != 'Identifier' )
			{
				foreach( $list_lignes[0] as $value ) 
				{
  						
					if( mb_detect_encoding($value)=="ASCII" )
						$value = iconv( "ASCII", "UTF-8", $value );
					else if ( mb_detect_encoding($value)=="Windows-1252" )
  						$value = iconv( "Windows-1252", "UTF-8", $value );
  					else $value = iconv( "Windows-1252", "UTF-8", $value );
  						
				}

				$split_one = explode('_', $list_lignes[0][9]);
				$zone = $split_one[0];
				$gipa = $split_one[1];
				$ligne = $split_one[2];
				$id = $split_one[3];

				$split_date_colonne_G = explode(' ', $list_lignes[0][6]);
				$date = $split_date_colonne_G[0];
				$date = str_replace( '.', '/', $date );
				$heure = $split_date_colonne_G[1];
				$heure_valid = $split_date_colonne_G[1];
				
			
				
				$query = "INSERT INTO questionnaire_s (id_global, enqueteur, zone, ligne, gipa,
				date, heure, heure_valid, Q_1_1, Q_1_2, Q_1_3, Q_1_4, Q_2_1, Q_2_2, Q_2_3, Q_2_4, Q_2_5,
				Q_3_1, Q_3_2, Q_3_3, Q_3_4, Q_3_5, Q_4_1, Q_4_1_obs, Q_4_2, Q_4_2_obs, Q_4_3, Q_4_3_obs,
				Q_4_4, Q_4_4_obs, Q_4_5, Q_4_5_obs, Q_4_6, Q_4_6_obs, Q_4_7, Q_4_7_obs, Q_4_8, Q_4_8_obs,
				Q_4_9, Q_4_9_obs, obs, valid, inopine) 

				VALUES(";

				$query .= $db->quote( $id ).",";
				$query .= $db->quote( $list_lignes[0][7] ).",";
				$query .= $db->quote( $zone ).",";
				$query .= $db->quote( $ligne ).",";
				$query .= $db->quote( $gipa ).",";
				$query .= $db->quote( $date ).",";
				$query .= $db->quote( $heure ).",";
				$query .= $db->quote( $heure_valid ).",";
				//Q_1_1
				$query .= $db->quote( $list_lignes[0][10] ).",";
				//Q_1_2
				$query .= $db->quote( $list_lignes[0][11] ).",";
				//Q_1_3
				$query .= $db->quote( $list_lignes[0][12] ).",";
				//Q_1_4
				$query .= $db->quote( $list_lignes[0][13] ).",";
				
				//Q_2_1
				if( $list_lignes[0][14] == "Oui" )$query .= $db->quote( "non" ).",";
				else{
					if( $list_lignes[0][15] == "")$query .= $db->quote( "non" ).",";
					else if( $list_lignes[0][15] == "Oui")$query .= $db->quote( $list_lignes[0][16] ).",";
					else $query .= $db->quote( $list_lignes[0][15] ).",";
				}
				//Q_2_2
				if( $list_lignes[0][14] == "Oui" )$query .= $db->quote( "non" ).",";
				else{
					if( $list_lignes[0][17] == "")$query .= $db->quote( "non" ).",";
					else if( $list_lignes[0][17] == "Oui")$query .= $db->quote( $list_lignes[0][18] ).",";
					else $query .= $db->quote( $list_lignes[0][17] ).",";
				}
				//Q_2_3
				if( $list_lignes[0][14] == "Oui" )$query .= $db->quote( "non" ).",";
				else{
					if( $list_lignes[0][19] == "")$query .= $db->quote( "non" ).",";
					else if( $list_lignes[0][19] == "Oui")$query .= $db->quote( $list_lignes[0][20] ).",";
					else $query .= $db->quote( $list_lignes[0][19] ).",";
				}
				//Q_2_4
				if( $list_lignes[0][14] == "Oui" )$query .= $db->quote( "non" ).",";
				else{
					if( $list_lignes[0][21] == "")$query .= $db->quote( "non" ).",";
					else if( $list_lignes[0][21] == "Oui")$query .= $db->quote( $list_lignes[0][22] ).",";
					else $query .= $db->quote( $list_lignes[0][21] ).",";
				}
				//Q_2_5
				if( $list_lignes[0][14] == "Oui" )$query .= $db->quote( "non" ).",";
				else{
					if( $list_lignes[0][23] == "")$query .= $db->quote( "non" ).",";
					else if( $list_lignes[0][23] == "Oui")$query .= $db->quote( $list_lignes[0][24] ).",";
					else $query .= $db->quote( $list_lignes[0][23] ).",";
				}
				//Q_3_1
				if( $list_lignes[0][14] == "Oui" )$query .= $db->quote( "non" ).",";
				else{
					if( $list_lignes[0][25] == "")$query .= $db->quote( "non" ).",";
					else if( $list_lignes[0][25] == "Oui")$query .= $db->quote( $list_lignes[0][26] ).",";
					else $query .= $db->quote( $list_lignes[0][25] ).",";
				}
				//Q_3_2
				if( $list_lignes[0][14] == "Oui" )$query .= $db->quote( "non" ).",";
				else{
					if( $list_lignes[0][27] == "")$query .= $db->quote( "non" ).",";
					else if( $list_lignes[0][27] == "Oui")$query .= $db->quote( $list_lignes[0][28] ).",";
					else $query .= $db->quote( $list_lignes[0][27] ).",";
				}
				//Q_3_3
				if( $list_lignes[0][14] == "Oui" )$query .= $db->quote( "non" ).",";
				else{
					if( $list_lignes[0][29] == "")$query .= $db->quote( "non" ).",";
					else if( $list_lignes[0][29] == "Oui")$query .= $db->quote( $list_lignes[0][30] ).",";
					else $query .= $db->quote( $list_lignes[0][29] ).",";
				}
				//Q_3_4
				if( $list_lignes[0][14] == "Oui" )$query .= $db->quote( "non" ).",";
				else{
					if( $list_lignes[0][31] == "")$query .= $db->quote( "non" ).",";
					else if( $list_lignes[0][31] == "Oui")$query .= $db->quote( $list_lignes[0][32] ).",";
					else $query .= $db->quote( $list_lignes[0][31] ).",";
				}
				//Q_3_5
				if( $list_lignes[0][14] == "Oui" )$query .= $db->quote( "non" ).",";
				else{
					if( $list_lignes[0][33] == "")$query .= $db->quote( "non" ).",";
					else if( $list_lignes[0][33] == "Oui")$query .= $db->quote( $list_lignes[0][34] ).",";
					else $query .= $db->quote( $list_lignes[0][33] ).",";
				}
				//Q_4_1
				if( $list_lignes[0][14] == "Oui" )$query .= $db->quote( "Présent" ).",";
				else{
					if( $list_lignes[0][35] == "")$query .= $db->quote( "Présent" ).",";
					else $query .= $db->quote( $list_lignes[0][35] ).",";
				}
				//Q_4_1_obs
				$query .= $db->quote( $list_lignes[0][36] ).",";

				//Q_4_2
				if( $list_lignes[0][14] == "Oui" )$query .= $db->quote( "Présent" ).",";
				else{
					if( $list_lignes[0][37] == "")$query .= $db->quote( "Présent" ).",";
					else $query .= $db->quote( $list_lignes[0][37] ).",";
				}
				//Q_4_2_obs
				$query .= $db->quote( $list_lignes[0][38] ).",";

				//Q_4_3
				if( $list_lignes[0][14] == "Oui" )$query .= $db->quote( "Présent" ).",";
				else{
					if( $list_lignes[0][39] == "")$query .= $db->quote( "Présent" ).",";
					else $query .= $db->quote( $list_lignes[0][39] ).",";
				}
				//Q_4_3_obs
				$query .= $db->quote( $list_lignes[0][40] ).",";

				//Q_4_4
				if( $list_lignes[0][14] == "Oui" )$query .= $db->quote( "Présent" ).",";
				else{
					if( $list_lignes[0][41] == "")$query .= $db->quote( "Présent" ).",";
					else $query .= $db->quote( $list_lignes[0][41] ).",";
				}
				//Q_4_4_obs
				$query .= $db->quote( $list_lignes[0][42] ).",";

				//Q_4_5
				if( $list_lignes[0][14] == "Oui" )$query .= $db->quote( "Présent" ).",";
				else{
					if( $list_lignes[0][43] == "")$query .= $db->quote( "Présent" ).",";
					else $query .= $db->quote( $list_lignes[0][43] ).",";
				}
				//Q_4_5_obs
				$query .= $db->quote( $list_lignes[0][44] ).",";

				//Q_4_6
				if( $list_lignes[0][14] == "Oui" )$query .= $db->quote( "Présent" ).",";
				else{
					if( $list_lignes[0][45] == "")$query .= $db->quote( "Présent" ).",";
					else $query .= $db->quote( $list_lignes[0][45] ).",";
				}
				//Q_4_6_obs
				$query .= $db->quote( $list_lignes[0][46] ).",";

				//Q_4_7
				if( $list_lignes[0][14] == "Oui" )$query .= $db->quote( "Présent" ).",";
				else{
					if( $list_lignes[0][47] == "")$query .= $db->quote( "Présent" ).",";
					else $query .= $db->quote( $list_lignes[0][47] ).",";
				}
				//Q_4_7_obs
				$query .= $db->quote( $list_lignes[0][48] ).",";

				//Q_4_8
				if( $list_lignes[0][14] == "Oui" )$query .= $db->quote( "Présent" ).",";
				else{
					if( $list_lignes[0][49] == "")$query .= $db->quote( "Présent" ).",";
					else $query .= $db->quote( $list_lignes[0][49] ).",";
				}
				//Q_4_8_obs
				$query .= $db->quote( $list_lignes[0][50] ).",";

				//Q_4_9
				if( $list_lignes[0][14] == "Oui" )$query .= $db->quote( "Présent" ).",";
				else{
					if( $list_lignes[0][51] == "")$query .= $db->quote( "Présent" ).",";
					else $query .= $db->quote( $list_lignes[0][51] ).",";
				}
				//Q_4_9_obs
				$query .= $db->quote( $list_lignes[0][52] ).",";

				//Obs
				$query .= $db->quote( $list_lignes[0][53] ).",";

				$query .= "DEFAULT, DEFAULT ";
				

				$query .= ")";
				
			$stmt = $db->prepare($query);
			$stmt->execute();
			
		}
			$db->commit();
			return true;
			
		} catch (\Exception $e) {
			
			$db->rollback();
			throw $e;
			return false;
		}
	}
}
