<?php

namespace AppBundle\Repository;

/**
 * CompteRenduRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompteRenduRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAll()
    {
        $db = $this->_em->getConnection();
		
		$query = "SELECT * FROM compte_rendu 
					ORDER BY substring(date_reunion, 7, 4) desc, 
                                        substring(date_reunion, 4, 2) desc, 
                                        substring(date_reunion, 1, 2) desc";
	
		$stmt = $db->prepare($query);
		$stmt->execute();
		$result = $stmt->fetchAll();

		return $result;
    }

	public function setBilanDb( $date, $name_file_bilan )
    {
        $db = $this->_em->getConnection();
		
		$query = "INSERT INTO compte_rendu (date_reunion, bilan) VALUES ('$date', '$name_file_bilan')";
	
		$stmt = $db->prepare($query);
		$stmt->execute();
    }

	public function setCompteRenduDb( $id, $name_file_cr )
    {
        $db = $this->_em->getConnection();
		
		$query = "UPDATE compte_rendu SET cr = '$name_file_cr' WHERE id=$id";
	
		$stmt = $db->prepare($query);
		$stmt->execute();
    }

	public function remove( $id )
    {
        $db = $this->_em->getConnection();
		
		$query = "DELETE FROM compte_rendu WHERE id=$id";
	
		$stmt = $db->prepare($query);
		$stmt->execute();
    }
}
