<?php

namespace AppBundle\Repository;

/**
 * EchangeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EchangeRepository extends \Doctrine\ORM\EntityRepository
{
    public function insert( $datas )
    {
		$db = $this->_em->getConnection();
		
        $query = "INSERT INTO echange (emetteur, emetteur_nom,document_nom,date,commentaire)
                    VALUES (
                        ".$db->quote($datas[0]).",
                        ".$db->quote($datas[1]).",
                        ".$db->quote($datas[2]).",
                        ".$db->quote($datas[3]).",
                        ".$db->quote($datas[4])."
                    )";
	
		$stmt = $db->prepare($query);
		$stmt->execute();
    }
    
    public function getAll( )
	{
		$db = $this->_em->getConnection();

        $query = "SELECT * FROM echange ORDER BY substring(date, 7, 4) desc, 
        substring(date, 4, 2) desc, 
        substring(date, 1, 2) desc";
	
		$stmt = $db->prepare($query);
		$stmt->execute();
		$result = $stmt->fetchAll();
	
		return $result;
    }
    
    public function remove( $id )
    {
		$db = $this->_em->getConnection();
		
        $query = "DELETE FROM echange WHERE id=$id";
	
		$stmt = $db->prepare($query);
		$stmt->execute();
    }
}
