<?php

namespace AppBundle\Repository;

/**
 * MatriculeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatriculeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAll( )
	{
		$db = $this->_em->getConnection();

		$query = "SELECT * FROM matricule";

		$stmt = $db->prepare( $query );
		$stmt->execute();
		$result = $stmt->fetchAll();

		return $result;
	}

    public function insert( $prestataireRessourceId, $matriculeOT )
    {
        $db = $this->_em->getConnection();
		
		$query = "INSERT INTO matricule (prestataire_ressource_id, matricule_ot) VALUES ($prestataireRessourceId, '$matriculeOT')";
	
		$stmt = $db->prepare($query);
		$stmt->execute();
    }

    public function remove( $id )
    {
        $db = $this->_em->getConnection();
		
		$query = "DELETE FROM matricule WHERE id=$id";
	
		$stmt = $db->prepare($query);
		$stmt->execute();
    }

    public function update( $id, $prestataireRessourceId, $matriculeOT )
    {
        $db = $this->_em->getConnection();
		
		$query = "UPDATE matricule SET prestataire_ressource_id = $prestataireRessourceId,
                                       matricule_ot='$matriculeOT' WHERE id=$id ";
	
		$stmt = $db->prepare($query);
		$stmt->execute();
    }
}
