<?php

namespace AppBundle\Repository;

/**
 * PaJsonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaJsonRepository extends \Doctrine\ORM\EntityRepository
{
    public function getZones( $date_to_extract )
	{
		$db = $this->_em->getConnection();
	
		$query = "SELECT DISTINCT(zone) as zone FROM questionnaire_s WHERE valid=2 
		AND date='".$date_to_extract."'
		 ORDER BY zone desc";
	
		$stmt = $db->prepare($query);
		$stmt->execute();
		$result = $stmt->fetchAll();
	
		return $result;
	}

	public function getLignes( $zone, $date_to_extract )
	{
		$db = $this->_em->getConnection();
	
		$query = "SELECT DISTINCT(ligne) as ligne FROM questionnaire_s WHERE valid=2 
					AND zone='".$zone."' AND date='".$date_to_extract."'
		 			ORDER BY zone desc";
	
		$stmt = $db->prepare($query);
		$stmt->execute();
		$result = $stmt->fetchAll();
	
		return $result;
	}

    public function getNbSaisiesByZones( $zone, $ligne, $date_to_extract )
	{
		$db = $this->_em->getConnection();
	
		$query = "SELECT COUNT(gipa) as NB FROM questionnaire_s WHERE valid=2 AND zone='".$zone."' 
					AND ligne='".$ligne."' AND date='".$date_to_extract."'";
	
		$stmt = $db->prepare($query);
		$stmt->execute();
		$result = $stmt->fetchAll();
	
		return $result;
	}
	
	public function getResultats( $zone, $ligne, $date_to_extract )
	{
		$db = $this->_em->getConnection();
	
		$query = "SELECT a.*, b.*, c.arret_id FROM questionnaire_s a
				LEFT JOIN fichier_global b ON a.gipa=b.numero_emplacement
						LEFT JOIN ref_arret_id c ON b.numero_emplacement=c.point_arret_numero
				WHERE valid=2 AND a.zone='".$zone."' AND a.ligne='".$ligne."' 
				AND a.date='".$date_to_extract."'
				GROUP BY a.id_global";
	
		$stmt = $db->prepare($query);
		$stmt->execute();
		$result = $stmt->fetchAll();
	
		return $result;
	}

	public function getResultatsByOne( $id )
	{
		$db = $this->_em->getConnection();
	
		$query = "SELECT a.*, b.*, c.arret_id FROM questionnaire_s a
				LEFT JOIN fichier_global b ON a.id_global=b.id
						LEFT JOIN ref_arret_id c ON b.numero_emplacement=c.point_arret_numero
				WHERE valid=2 AND a.id_global=$id
				GROUP BY a.id_global";
	
		$stmt = $db->prepare($query);
		$stmt->execute();
		$result = $stmt->fetchAll();
	
		return $result;
	}

	public function getMesureDate( $zone, $date, $order )
	{
		$db = $this->_em->getConnection();
	
		$query = "SELECT date, heure FROM questionnaire_s WHERE zone='$zone' AND date='$date' ORDER BY heure $order LIMIT 1";

		$stmt = $db->prepare($query);
		$stmt->execute();
		$result = $stmt->fetchAll();
	
		return $result;
	}

    public function getligneNumero( $nom_arret, $ligne_libelle, $gipa )
	{
		$db = $this->_em->getConnection();
	
		$query = "SELECT DISTINCT(ligne_numero) as ligne_numero, ligne_id FROM fichier_global
				WHERE libelle_commercial='".$ligne_libelle."' AND numero_emplacement='".$gipa."'";

		$stmt = $db->prepare($query);
		$stmt->execute();
		$result = $stmt->fetchAll();
	
		return $result;
	}

	
	/*public function getPointsArretsId(  $ligne_libelle, $ligne_numero, $zone, $order )
	{
		$db = $this->_em->getConnection();
	
		$query = "SELECT a.*, b.arret_id FROM fichier_global a
					LEFT JOIN ref_arret_id b
					ON a.numero_emplacement=b.point_arret_numero
				WHERE a.libelle_commercial='".$ligne_libelle."' 
				AND a.ligne='".$ligne_numero."' AND zone='".$zone."' GROUP BY point_arret_numero  
				ORDER BY a.ordre ".$order." LIMIT 1";echo $query;
	
		$stmt = $db->prepare($query);
		$stmt->execute();
		$result = $stmt->fetchAll();
	
		return $result;
	}*/

	public function getPointsArretsId(  $ligne_id, $ligne_numero, $mois, $order )
	{
		$db = $this->_em->getConnection();
	
		$query = "SELECT numero_arret FROM fichier_global
					WHERE ligne_id=$ligne_id AND ligne_numero=$ligne_numero 
					AND mois=$mois
					ORDER BY ordre ".$order." LIMIT 1";

		$stmt = $db->prepare($query);
		$stmt->execute();
		$result = $stmt->fetchAll();
	
		return $result;
	}
	
   /* public function getPointsArretsId( $ligne_libelle, $ligne_numero, $id, $order )
	{
		$db = $this->_em->getConnection();
	
		$query = "SELECT a.*, b.arret_id FROM fichier_global a
					LEFT JOIN ref_arret_id b
					ON a.numero_emplacement=b.point_arret_numero
				WHERE a.libelle_commercial='".$ligne_libelle."' 
				AND a.ligne='".$ligne_numero."' AND a.id=$id GROUP BY point_arret_numero  
				ORDER BY a.ordre ".$order." LIMIT 1";

		$stmt = $db->prepare($query);
		$stmt->execute();
		$result = $stmt->fetchAll();
	
		return $result;
	}*/

    public function getligneID( $ligne_libelle, $gipa )
	{
		$db = $this->_em->getConnection();
	
		$query = "SELECT DISTINCT(ligne_id) as ligne_id FROM 
					ref_arret_id WHERE ligne_libelle='".$ligne_libelle."'
					AND point_arret_numero='".$gipa."'";
	
		$stmt = $db->prepare($query);
		$stmt->execute();
		$result = $stmt->fetchAll();
	
		return $result;
	}

    public function getInfosSaisie( $zone, $ligne, $date_to_extract )
	{
		$db = $this->_em->getConnection();
	
		$query = "SELECT a.*,
				  b.* FROM zone_enq a
				LEFT JOIN fichier_global b ON a.zone=b.zone
				
				WHERE a.zone='".$zone."' AND b.libelle_commercial='".$ligne."' 
				AND a.date='".$date_to_extract."'
				ORDER BY ordre asc ";
	
		$stmt = $db->prepare($query);
		$stmt->execute();
		$result = $stmt->fetchAll();
	
		return $result;
	}

	public function getInfosSaisieByOne( $id )
	{
		$db = $this->_em->getConnection();
	
		$query = "SELECT a.*,
				  b.* FROM zone_enq a
				LEFT JOIN fichier_global b ON a.zone=b.zone
				WHERE b.id=$id
				ORDER BY ordre asc ";
	
		$stmt = $db->prepare($query);
		$stmt->execute();
		$result = $stmt->fetchAll();
	
		return $result;
	}

	public function setStatutOne( $id, $statut )
	{
		$db = $this->_em->getConnection();
	
		$query = "UPDATE questionnaire_s SET `generated`=$statut, generated_date=NOW()
				WHERE id_global=$id ";
	
		$stmt = $db->prepare($query);
		$stmt->execute();
	}

	public function getPaId( $nomPA, $direction, $ligne_id, $ligne_libelle, $ligne_numero )
	{
		$db = $this->_em->getConnection();
	
		$query = "SELECT numero_arret
				FROM fichier_global
				WHERE ligne_id=$ligne_id AND ligne_numero=$ligne_numero AND libelle_commercial='$ligne_libelle'
				AND nom_arret=".$db->quote( strtoupper($nomPA) )." 
				AND destination=".$db->quote( strtoupper($direction) );

		$stmt = $db->prepare($query);
		$stmt->execute();
		$result = $stmt->fetchAll();
	
		return $result;
	}

	public function getMatricule( $matricule_ot )
	{
		$db = $this->_em->getConnection();
	
		$query = "SELECT prestataire_ressource_id
				FROM matricule
				WHERE matricule_ot='$matricule_ot'";

		$stmt = $db->prepare($query);
		$stmt->execute();
		$result = $stmt->fetchAll();
	
		return $result;
	}
}
