<?php

namespace AppBundle\Repository;

/**
 * QuestionnaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionnaireRepository extends \Doctrine\ORM\EntityRepository
{
	public function getByFilter( $typeFilter, $dataFilter )
	{//$em->createQuery
		/* TEST AVEC QUERY SQL CLASSIQUE + CAST ENTITE, FONCTIONNE MOYENNEMENT AVEC GETTER / SETTER
		$db = $this->_em->getConnection();

		$query_filter = "";
		if( $typeFilter == "enqueteur" )$query_filter .= " enq = ".$dataFilter;
		if( $typeFilter == "ligne" )$query_filter .= " ligne = ".$dataFilter;
		if( $typeFilter == "date" )$query_filter .= " date = ".$dataFilter;

		$query = "SELECT * FROM questionnaire_s WHERE ".$query_filter;

		$stmt = $db->prepare( $query );
		$stmt->execute();

		$result = $stmt->fetchObject(\PDO::FETCH_CLASS, "AppBundle\Entity\Questionnaire");

		return $result;*/

		$qb = $this->createQueryBuilder('q');

		if( $typeFilter == "enqueteur" )
		{
			$qb
				->select('q')
				->where('q.enq = :numEnqueteur')
				->orderBy('q.date', 'desc')
				->setParameter('numEnqueteur', $dataFilter);
		}

		else if( $typeFilter == "ligne" )
		{
			$qb
				->select('q')
				->where('q.ligne = :ligne')
				->orderBy('q.date', 'desc')
				->setParameter('ligne', $dataFilter);
		}

		else if( $typeFilter == "date" )
		{
			$qb
				->select('q')
				->where('q.date = :date')
				->orderBy('q.date', 'desc')
				->setParameter('date', $dataFilter);
		}

		else if( $typeFilter == "arretMontee" )
		{
			$qb
				->select('q')
				->where('q.arretMontee = :arret_montee')
				->orderBy('q.date', 'desc')
				->setParameter('arret_montee', $dataFilter);
		}

		return $qb->getQuery()->getResult();
	}

	public function listEnqueteurs( $mois_to_show )
	{
		$db = $this->_em->getConnection();

		$query = "SELECT DISTINCT(enq) as enq FROM $mois_to_show";

		$stmt = $db->prepare( $query );
		$stmt->execute();
		$result = $stmt->fetchAll();

		return $result;
	}

	public function listLignes( $mois_to_show )
	{
		$db = $this->_em->getConnection();

		$query = "SELECT DISTINCT(ligne) as ligne FROM $mois_to_show";

		$stmt = $db->prepare( $query );
		$stmt->execute();
		$result = $stmt->fetchAll();

		return $result;
	}

	public function listDates( $mois_to_show )
	{
		$db = $this->_em->getConnection();

		$query = "SELECT DISTINCT(date) as date FROM $mois_to_show";

		$stmt = $db->prepare( $query );
		$stmt->execute();
		$result = $stmt->fetchAll();

		return $result;
	}

	public function getAll( )
	{
		$db = $this->_em->getConnection();

		$query = "SELECT * FROM questionnaire_s ORDER BY date_debut_mesure asc";

		$stmt = $db->prepare( $query );
		$stmt->execute();
		$result = $stmt->fetchAll();

		return $result;
	}

	public function listItems( $item, $table )
	{
		$db = $this->_em->getConnection();

		$query = "SELECT DISTINCT( $item ) as  $item FROM $table";
		$stmt = $db->prepare( $query );
		$stmt->execute();
		$result = $stmt->fetchAll();

		return $result;
	}

	public function listMois()
	{
		$db = $this->_em->getConnection();

		$query = "SELECT DISTINCT( SUBSTR(date, 4, 2) ) as date, ( SUBSTR(date_debut_mesure, 7, 4) ) as date_debut_mesure FROM questionnaire_s";

		$stmt = $db->prepare( $query );
		$stmt->execute();
		$result = $stmt->fetchAll();

		return $result;
	}

	public function listPointsArrets()
	{
		$db = $this->_em->getConnection();

		$query = "SELECT DISTINCT(arret_montee) as arret_montee FROM questionnaire_s";

		$stmt = $db->prepare( $query );
		$stmt->execute();
		$result = $stmt->fetchAll();

		return $result;
	}

	public function insertDatas( $list_lignes, $createdAt, $heureFin, $heureDescente, $date, $heureMontee )
	{ 
		$db = $this->_em->getConnection();
		
		try {
		
			$db->beginTransaction();
		
		
			if( $list_lignes[0][0] != 'Identifier' )
			{
				foreach( $list_lignes[0] as &$value ) 
				{
  						
					if( mb_detect_encoding($value)=="ASCII" )
						$value = iconv( "ASCII", "UTF-8", $value );
					else if ( mb_detect_encoding($value)=="Windows-1252" )
  						$value = iconv( "Windows-1252", "UTF-8", $value );
  					//else $value = iconv( "Windows-1252", "UTF-8", $value );
  						
				}

				$enq = $list_lignes[0][5];
				$ligne = $list_lignes[0][8];

				//Heure grille
				$dateExplode = explode(' ', $date);

				$dateGrille = str_replace( '.', '_', @$dateExplode[0] );
				$heureGrille = str_replace( ':', 'H', @$dateExplode[1] );
				$dateInsert = explode( '_', $dateGrille );
				
				$grille = $enq.'_LIGNE_'.$ligne.'_DATE_'.$dateGrille.'_HEURE_'.$heureGrille;
				
				$date_planning_explode = explode('.', $dateExplode[0]);
				$num_planning = $enq.'_'.@$date_planning_explode[1].'_'.@$date_planning_explode[2];

				$nuit_brute = explode(' ', $list_lignes[0][7]);


				switch ( $nuit_brute[0] ) {
					case 'lundi':
							$nuit = 1;
						break;
					case 'mardi':
							$nuit = 2;
						break;
					case 'mercredi':
							$nuit = 3;
						break;
					case 'jeudi':
							$nuit = 4;
						break;
					case 'vendredi':
							$nuit = 5;
						break;
					case 'samedi':
							$nuit = 6;
						break;
					
					default:
						$nuit = '1';
						break;
				}
				
				$query = "INSERT INTO questionnaire_s ( id, grille, enq, num_planning, date_debut_mesure,
							date_fin_mesure, MR_H_descente, date, nuit, ligne, coquille, arret_montee, heure_montee, direction, biv_indice, biv_indice_detail,
								biv_direction, biv_direction_detail, biv_attente, biv_attente_detail,
								MR_2_1, MR_2_1_detail, Q_2_1, Q_2_2, Q_2_3, Q_2_4,
								Q_3_1, Q_3_1_detail, Q_3_2, Q_3_2_detail, Q_3_3, Q_3_3_detail,
								Q_3_4, Q_3_4_detail, Q_4_1, Q_4_1_detail, Q_4_2, Q_4_2_detail, Q_4_3,Q_4_3_detail,
								Q_5_1, Q_5_2, Q_5_3, Q_5_4, Q_5_5, Q_5_6, Q_5_7, Q_5_8,
								Q_6_1, Q_6_2, Q_6_3, Q_6_4, Q_6_5, Q_6_6, Q_6_7, Q_6_8, Q_6_9,
								Q_6_10, Q_6_11, Q_6_12, Q_6_13, Q_6_14, Q_7_1, MR_3_1, MR_3_2,
								MR_4_1, MR_4_2, MR_5_1, MR_5_2, MR_5_3, MR_5_4, MR_5_5, MR_6_1,
								MR_6_2, MR_6_3, MR_6_4, MR_7_1, MR_7_2, MR_7_3, MR_7_4, MR_7_5
								, MR_7_6, MR_7_7, MR_2_1_bis, MR_2_1_detail_bis, obs, valid, arret_descente, generated_date ) 

				

				VALUES(";

				$query .= "DEFAULT,";
				$query .= $db->quote( $grille ).",";
				$query .= $db->quote( $enq ).",";
				$query .= $db->quote( $num_planning ).",";
				$query .= $db->quote( $createdAt ).",";
				$query .= $db->quote( $heureFin ).",";
				$query .= $db->quote( $heureDescente ).",";
				$query .= $db->quote( $dateInsert[0].'/'.$dateInsert[1] ).",";
				$query .= $db->quote( $nuit ).",";
				$query .= $db->quote( $ligne ).",";
				$query .= $db->quote( $list_lignes[0][13] ).",";
				$query .= $db->quote( $list_lignes[0][10] ).",";
				$query .= $db->quote( $heureMontee ).",";
				$query .= $db->quote( $list_lignes[0][9] ).",";
				$query .= $db->quote( $list_lignes[0][15] ).",";
				$query .= $db->quote( $list_lignes[0][16] ).",";
				$query .= $db->quote( $list_lignes[0][17] ).",";
				$query .= $db->quote( $list_lignes[0][18] ).",";
				$query .= $db->quote( $list_lignes[0][19] ).",";
				$query .= $db->quote( $list_lignes[0][20] ).",";
				$query .= $db->quote( $list_lignes[0][21] ).",";
				$query .= $db->quote( $list_lignes[0][22] ).",";

				if( $list_lignes[0][24]=='Oui' )
				{
					//Q 2.1 à Q 2.4
					$query .= $db->quote( "non" ).",";
					$query .= $db->quote( "non" ).",";
					$query .= $db->quote( "non" ).",";
					$query .= $db->quote( "non" ).",";

					//Q 3.1 à Q 3.4
					$query .= $db->quote( "Oui" ).",";
					$query .=  "NULL".",";
					$query .= $db->quote( "Oui" ).",";
					$query .=  "NULL".",";
					$query .= $db->quote( "Oui" ).",";
					$query .=  "NULL".",";
					$query .= $db->quote( "Oui" ).",";
					$query .=  "NULL".",";

					//Q 4.1 à Q 4.3
					$query .= $db->quote( "Oui" ).",";
					$query .=  "NULL".",";
					$query .= $db->quote( "Oui" ).",";
					$query .=  "NULL".",";
					$query .= $db->quote( "Oui" ).",";
					$query .=  "NULL".",";

					//Q 5.1 à Q 5.8
					$query .= $db->quote( "Oui" ).",";
					$query .= $db->quote( "Oui" ).",";
					$query .= $db->quote( "Oui" ).",";
					$query .= $db->quote( "Oui" ).",";
					$query .= $db->quote( "Oui" ).",";
					$query .= $db->quote( "Oui" ).",";
					$query .= $db->quote( "Oui" ).",";
					$query .= $db->quote( "Oui" ).",";

					//Q 6.1 à Q 7.1
					$query .= $db->quote( "non" ).",";
					$query .= $db->quote( "non" ).",";
					$query .= $db->quote( "non" ).",";
					$query .= $db->quote( "non" ).",";
					$query .= $db->quote( "non" ).",";
					$query .= $db->quote( "non" ).",";
					$query .= $db->quote( "non" ).",";
					$query .= $db->quote( "non" ).",";
					$query .= $db->quote( "non" ).",";
					$query .= $db->quote( "non" ).",";
					$query .= $db->quote( "non" ).",";
					$query .= $db->quote( "non" ).",";
					$query .= $db->quote( "non" ).",";
					$query .= $db->quote( "non" ).",";
					$query .= $db->quote( "non" ).",";
				}
				else
				{
					//Q 2.1 à Q 2.4
					if( $list_lignes[0][25]=='Oui' )$query .= $db->quote( $list_lignes[0][26] ).",";
						else $query .= $db->quote( "non" ).",";
					if( $list_lignes[0][27]=='Oui' )$query .= $db->quote( $list_lignes[0][28] ).",";
						else $query .= $db->quote( "non" ).",";
					if( $list_lignes[0][29]=='Oui' )$query .= $db->quote( $list_lignes[0][30] ).",";
						else $query .= $db->quote( "non" ).",";
					if( $list_lignes[0][31]=='Oui' )$query .= $db->quote( $list_lignes[0][32] ).",";
						else $query .= $db->quote( "non" ).",";

					//Q 3.1 
					if( empty($list_lignes[0][33]) )
						{ $query .= $db->quote( "Oui" ).","; $query .=  "NULL".",";}
					else 
						{ 
							if($list_lignes[0][33]=='Oui' )
							{
								$query .= $db->quote( $list_lignes[0][33] ).",";
								$query .=  "NULL".",";
							}
							else
							{
								$query .= $db->quote( $list_lignes[0][33] ).","; 
								$query .= $db->quote( $list_lignes[0][34] ).",";
							}
						}
					
					//Q 3.2 
					if( empty($list_lignes[0][35]) )
						{ $query .= $db->quote( "Oui" ).","; $query .=  "NULL".",";}
					else 
						{ 
							if($list_lignes[0][35]=='Oui' )
							{
								$query .= $db->quote( $list_lignes[0][35] ).",";
								$query .=  "NULL".",";
							}
							else
							{
								$query .= $db->quote( $list_lignes[0][35] ).","; 
								$query .= $db->quote( $list_lignes[0][36] ).",";
							}
						}
					
					//Q 3.3 
					if( empty($list_lignes[0][37]) )
						{ $query .= $db->quote( "Oui" ).","; $query .=  "NULL".",";}
					else 
						{ 
							if($list_lignes[0][37]=='Oui' )
							{
								$query .= $db->quote( $list_lignes[0][37] ).",";
								$query .=  "NULL".",";
							}
							else
							{
								$query .= $db->quote( $list_lignes[0][37] ).","; 
								$query .= $db->quote( $list_lignes[0][38] ).",";
							}
						}
					
					//Q 3.4 
					if( empty($list_lignes[0][39]) )
						{ $query .= $db->quote( "Oui" ).","; $query .=  "NULL".",";}
					else 
						{ 
							if($list_lignes[0][39]=='Oui' )
							{
								$query .= $db->quote( $list_lignes[0][39] ).",";
								$query .=  "NULL".",";
							}
							else
							{
								$query .= $db->quote( $list_lignes[0][39] ).","; 
								$query .= $db->quote( $list_lignes[0][40] ).",";
							}
						}

					//Q 4.1
					if( empty($list_lignes[0][41]) )
						{ $query .= $db->quote( "Oui" ).","; $query .=  "NULL".",";}
					else 
						{ 
							if($list_lignes[0][41]=='Oui' )
							{
								$query .= $db->quote( $list_lignes[0][41] ).",";
								$query .=  "NULL".",";
							}
							else
							{
								$query .= $db->quote( $list_lignes[0][41] ).","; 
								$query .= $db->quote( $list_lignes[0][42] ).",";
							}
						}

					//Q 4.2
					if( empty($list_lignes[0][43]) )
						{ $query .= $db->quote( "Oui" ).","; $query .=  "NULL".",";}
					else 
						{ 
							if($list_lignes[0][43]=='Oui' )
							{
								$query .= $db->quote( $list_lignes[0][43] ).",";
								$query .=  "NULL".",";
							}
							else
							{
								$query .= $db->quote( $list_lignes[0][43] ).","; 
								$query .= $db->quote( $list_lignes[0][44] ).",";
							}
						}

					//Q 4.3
					if( empty($list_lignes[0][45]) )
						{ $query .= $db->quote( "Oui" ).","; $query .=  "NULL".",";}
					else 
						{ 
							if($list_lignes[0][45]=='Oui' )
							{
								$query .= $db->quote( $list_lignes[0][45] ).",";
								$query .=  "NULL".",";
							}
							else
							{
								$query .= $db->quote( $list_lignes[0][45] ).","; 
								$query .= $db->quote( $list_lignes[0][46] ).",";
							}
						}

					// Q 5.1
					if( empty( $list_lignes[0][47] ) || $list_lignes[0][47]=='Oui' )$query .= $db->quote( "Oui" ).",";
					else if($list_lignes[0][47]=='NO')$query .= $db->quote( "NO" ).",";
					else $query .= $db->quote( $list_lignes[0][47] ."_". $list_lignes[0][48] ).",";
					// Q 5.2
					if( empty( $list_lignes[0][49] ) || $list_lignes[0][49]=='Oui' )$query .= $db->quote( "Oui" ).",";
					else if($list_lignes[0][49]=='NO')$query .= $db->quote( "NO" ).",";
					else $query .= $db->quote( $list_lignes[0][49] ."_". $list_lignes[0][50] ).",";
					// Q 5.3
					if( empty( $list_lignes[0][51] ) || $list_lignes[0][51]=='Oui' )$query .= $db->quote( "Oui" ).",";
					else if($list_lignes[0][51]=='NO')$query .= $db->quote( "NO" ).",";
					else $query .= $db->quote( $list_lignes[0][51] ."_". $list_lignes[0][52] ).",";
					// Q 5.4
					if( empty( $list_lignes[0][53] ) || $list_lignes[0][53]=='Oui' )$query .= $db->quote( "Oui" ).",";
					else if($list_lignes[0][53]=='NO')$query .= $db->quote( "NO" ).",";
					else $query .= $db->quote( $list_lignes[0][53] ."_". $list_lignes[0][54] ).",";
					// Q 5.5
					if( empty( $list_lignes[0][55] ) || $list_lignes[0][55]=='Oui' )$query .= $db->quote( "Oui" ).",";
					else if($list_lignes[0][55]=='NO')$query .= $db->quote( "NO" ).",";
					else $query .= $db->quote( $list_lignes[0][55] ."_". $list_lignes[0][56] ).",";
					// Q 5.6
					if( empty( $list_lignes[0][57] ) || $list_lignes[0][57]=='Oui' )$query .= $db->quote( "Oui" ).",";
					else if($list_lignes[0][57]=='NO')$query .= $db->quote( "NO" ).",";
					else $query .= $db->quote( $list_lignes[0][57] ."_". $list_lignes[0][58] ).",";
					// Q 5.7
					if( empty( $list_lignes[0][59] ) || $list_lignes[0][59]=='Oui' )$query .= $db->quote( "Oui" ).",";
					else if($list_lignes[0][59]=='NO')$query .= $db->quote( "NO" ).",";
					else $query .= $db->quote( $list_lignes[0][59] ."_". $list_lignes[0][60] ).",";
					// Q 5.8
					if( empty( $list_lignes[0][61] ) || $list_lignes[0][61]=='Oui' )$query .= $db->quote( "Oui" ).",";
					else if($list_lignes[0][61]=='NO')$query .= $db->quote( "NO" ).",";
					else $query .= $db->quote( $list_lignes[0][61] ."_". $list_lignes[0][62] ).",";
				
					//Q 6.1
					if( empty( $list_lignes[0][63] ) || $list_lignes[0][63]=='non' )$query .= $db->quote( "non" ).",";
					else if($list_lignes[0][63]=='NO')$query .= $db->quote( "NO" ).",";
					else $query .= $db->quote( $list_lignes[0][64] ).",";
					//Q 6.2
					if( empty( $list_lignes[0][65] ) || $list_lignes[0][65]=='non' )$query .= $db->quote( "non" ).",";
					else if($list_lignes[0][65]=='NO')$query .= $db->quote( "NO" ).",";
					else $query .= $db->quote( $list_lignes[0][66] ).",";
					//Q 6.3
					if( empty( $list_lignes[0][67] ) || $list_lignes[0][67]=='non' )$query .= $db->quote( "non" ).",";
					else if($list_lignes[0][67]=='NO')$query .= $db->quote( "NO" ).",";
					else $query .= $db->quote( $list_lignes[0][68] ).",";
					//Q 6.4
					if( empty( $list_lignes[0][69] ) || $list_lignes[0][69]=='non' )$query .= $db->quote( "non" ).",";
					else if($list_lignes[0][69]=='NO')$query .= $db->quote( "NO" ).",";
					else $query .= $db->quote( $list_lignes[0][70] ).",";
					//Q 6.5
					if( empty( $list_lignes[0][71] ) || $list_lignes[0][71]=='non' )$query .= $db->quote( "non" ).",";
					else if($list_lignes[0][71]=='NO')$query .= $db->quote( "NO" ).",";
					else $query .= $query .= $db->quote( $list_lignes[0][72] ).",";
					//Q 6.6
					if( empty( $list_lignes[0][73] ) || $list_lignes[0][73]=='non' )$query .= $db->quote( "non" ).",";
					else if($list_lignes[0][73]=='NO')$query .= $db->quote( "NO" ).",";
					else $query .= $db->quote( $list_lignes[0][74] ).",";
					//Q 6.7
					if( empty( $list_lignes[0][75] ) || $list_lignes[0][75]=='non' )$query .= $db->quote( "non" ).",";
					else if($list_lignes[0][75]=='NO')$query .= $db->quote( "NO" ).",";
					else $query .= $db->quote( $list_lignes[0][76] ).",";
					//Q 6.8
					if( empty( $list_lignes[0][77] ) || $list_lignes[0][77]=='non' )$query .= $db->quote( "non" ).",";
					else if($list_lignes[0][77]=='NO')$query .= $db->quote( "NO" ).",";
					else $query .= $db->quote( $list_lignes[0][78] ).",";
					//Q 6.9
					if( empty( $list_lignes[0][79] ) || $list_lignes[0][79]=='non' )$query .= $db->quote( "non" ).",";
					else if($list_lignes[0][79]=='NO')$query .= $db->quote( "NO" ).",";
					else $query .= $db->quote( $list_lignes[0][80] ).",";
					//Q 6.10
					if( empty( $list_lignes[0][81] ) || $list_lignes[0][81]=='non' )$query .= $db->quote( "non" ).",";
					else if($list_lignes[0][81]=='NO')$query .= $db->quote( "NO" ).",";
					else $query .= $db->quote( $list_lignes[0][82] ).",";
					//Q 6.11
					if( empty( $list_lignes[0][83] ) || $list_lignes[0][83]=='non' )$query .= $db->quote( "non" ).",";
					else if($list_lignes[0][83]=='NO')$query .= $db->quote( "NO" ).",";
					else $query .= $db->quote( $list_lignes[0][84] ).",";
					//Q 6.12
					if( empty( $list_lignes[0][85] ) || $list_lignes[0][85]=='non' )$query .= $db->quote( "non" ).",";
					else if($list_lignes[0][85]=='NO')$query .= $db->quote( "NO" ).",";
					else $query .= $db->quote( $list_lignes[0][86] ).",";
					//Q 6.13
					if( empty( $list_lignes[0][87] ) || $list_lignes[0][87]=='non' )$query .= $db->quote( "non" ).",";
					else if($list_lignes[0][87]=='NO')$query .= $db->quote( "NO" ).",";
					else $query .= $db->quote( $list_lignes[0][88] ).",";
					//Q 6.14
					if( empty( $list_lignes[0][89] ) || $list_lignes[0][89]=='non' )$query .= $db->quote( "non" ).",";
					else if($list_lignes[0][89]=='NO')$query .= $db->quote( "NO" ).",";
					else $query .= $db->quote( $list_lignes[0][90] ).",";
					//Q 7.1
					if( empty( $list_lignes[0][91] ) || $list_lignes[0][91]=='non' )$query .= $db->quote( "non" ).",";
					else if($list_lignes[0][91]=='NO')$query .= $db->quote( "NO" ).",";
					else $query .= $db->quote( $list_lignes[0][92] ).",";
				}

				if( $list_lignes[0][93]=='Oui' )
				{
					$query .= $db->quote( "non" ).",";
					$query .= $db->quote( "non" ).",";
					$query .= $db->quote( "non" ).",";
					$query .= $db->quote( "non" ).",";
					$query .= $db->quote( "non" ).",";
					$query .= $db->quote( "non" ).",";
					$query .= $db->quote( "non" ).",";
					$query .= $db->quote( "non" ).",";
					$query .= $db->quote( "non" ).",";
					$query .= $db->quote( "non" ).",";
					$query .= $db->quote( "non" ).",";
					$query .= $db->quote( "non" ).",";
					$query .= $db->quote( "non" ).",";
					$query .= $db->quote( "non" ).",";
					$query .= $db->quote( "non" ).",";
					$query .= $db->quote( "non" ).",";
					$query .= $db->quote( "non" ).",";
					$query .= $db->quote( "non" ).",";
					$query .= $db->quote( "non" ).",";
					$query .= $db->quote( "non" ).",";
				}
				else
				{
					//MR 3.1
					if( empty( $list_lignes[0][94] ) || $list_lignes[0][94]=='non' )$query .= $db->quote( "non" ).",";
					else if($list_lignes[0][94]=='NO')$query .= $db->quote( "NO" ).",";
					else $query .= $db->quote( $list_lignes[0][95] ).",";

					//MR 3.2
					if( empty( $list_lignes[0][96] ) || $list_lignes[0][96]=='non' )$query .= $db->quote( "non" ).",";
					else if($list_lignes[0][96]=='NO')$query .= $db->quote( "NO" ).",";
					else $query .= $db->quote( $list_lignes[0][97] ).",";

					//MR 4.1
					if( empty( $list_lignes[0][98] ) || $list_lignes[0][98]=='non' )$query .= $db->quote( "non" ).",";
					else if($list_lignes[0][98]=='NO')$query .= $db->quote( "NO" ).",";
					else $query .= $db->quote( $list_lignes[0][99] ).",";

					//MR 4.2
					if( empty( $list_lignes[0][100] ) || $list_lignes[0][100]=='non' )$query .= $db->quote( "non" ).",";
					else if($list_lignes[0][100]=='NO')$query .= $db->quote( "NO" ).",";
					else $query .= $db->quote( $list_lignes[0][101] ).",";

					//MR 5.1
					if( empty( $list_lignes[0][102] ) || $list_lignes[0][102]=='non' )$query .= $db->quote( "non" ).",";
					else if($list_lignes[0][102]=='NO')$query .= $db->quote( "NO" ).",";
					else $query .= $db->quote( $list_lignes[0][103] ).",";

					//MR 5.2
					if( empty( $list_lignes[0][104] ) || $list_lignes[0][104]=='non' )$query .= $db->quote( "non" ).",";
					else if($list_lignes[0][104]=='NO')$query .= $db->quote( "NO" ).",";
					else $query .= $db->quote( $list_lignes[0][105] ).",";

					//MR 5.3
					if( empty( $list_lignes[0][106] ) || $list_lignes[0][106]=='non' )$query .= $db->quote( "non" ).",";
					else if($list_lignes[0][106]=='NO')$query .= $db->quote( "NO" ).",";
					else $query .= $db->quote( $list_lignes[0][107] ).",";

					//MR 5.4
					if( empty( $list_lignes[0][108] ) || $list_lignes[0][108]=='non' )$query .= $db->quote( "non" ).",";
					else if($list_lignes[0][108]=='NO')$query .= $db->quote( "NO" ).",";
					else $query .= $db->quote( $list_lignes[0][109] ).",";

					//MR 5.5
					if( empty( $list_lignes[0][110] ) || $list_lignes[0][110]=='non' )$query .= $db->quote( "non" ).",";
					else if($list_lignes[0][110]=='NO')$query .= $db->quote( "NO" ).",";
					else $query .= $db->quote( $list_lignes[0][111] ).",";

					//MR 6.1
					if( empty( $list_lignes[0][112] ) || $list_lignes[0][112]=='non' )$query .= $db->quote( "non" ).",";
					else if($list_lignes[0][112]=='NO')$query .= $db->quote( "NO" ).",";
					else $query .= $db->quote( $list_lignes[0][113] ).",";

					//MR 6.2
					if( empty( $list_lignes[0][114] ) || $list_lignes[0][114]=='non' )$query .= $db->quote( "non" ).",";
					else if($list_lignes[0][114]=='NO')$query .= $db->quote( "NO" ).",";
					else $query .= $db->quote( $list_lignes[0][115] ).",";

					//MR 6.3
					if( empty( $list_lignes[0][116] ) || $list_lignes[0][116]=='non' )$query .= $db->quote( "non" ).",";
					else if($list_lignes[0][116]=='NO')$query .= $db->quote( "NO" ).",";
					else $query .= $db->quote( $list_lignes[0][117] ).",";

					//MR 6.4
					if( empty( $list_lignes[0][118] ) || $list_lignes[0][118]=='non' )$query .= $db->quote( "non" ).",";
					else if($list_lignes[0][118]=='NO')$query .= $db->quote( "NO" ).",";
					else $query .= $db->quote( $list_lignes[0][119] ).",";

					//MR 7.1
					if( empty( $list_lignes[0][120] ) || $list_lignes[0][120]=='non' )$query .= $db->quote( "non" ).",";
					else if($list_lignes[0][120]=='NO')$query .= $db->quote( "NO" ).",";
					else $query .= $db->quote( $list_lignes[0][121] ).",";

					//MR 7.2
					if( empty( $list_lignes[0][122] ) || $list_lignes[0][122]=='non' )$query .= $db->quote( "non" ).",";
					else if($list_lignes[0][122]=='NO')$query .= $db->quote( "NO" ).",";
					else $query .= $db->quote( $list_lignes[0][123] ).",";

					//MR 7.3
					if( empty( $list_lignes[0][124] ) || $list_lignes[0][124]=='non' )$query .= $db->quote( "non" ).",";
					else if($list_lignes[0][124]=='NO')$query .= $db->quote( "NO" ).",";
					else $query .= $db->quote( $list_lignes[0][125] ).",";

					//MR 7.4
					if( empty( $list_lignes[0][126] ) || $list_lignes[0][126]=='non' )$query .= $db->quote( "non" ).",";
					else if($list_lignes[0][126]=='NO')$query .= $db->quote( "NO" ).",";
					else $query .= $db->quote( $list_lignes[0][127] ).",";

					//MR 7.5
					if( empty( $list_lignes[0][128] ) || $list_lignes[0][128]=='non' )$query .= $db->quote( "non" ).",";
					else if($list_lignes[0][128]=='NO')$query .= $db->quote( "NO" ).",";
					else $query .= $db->quote( $list_lignes[0][129] ).",";

					//MR 7.6
					if( empty( $list_lignes[0][130] ) || $list_lignes[0][130]=='non' )$query .= $db->quote( "non" ).",";
					else if($list_lignes[0][130]=='NO')$query .= $db->quote( "NO" ).",";
					else $query .= $db->quote( $list_lignes[0][131] ).",";

					//MR 7.7
					if( empty( $list_lignes[0][132] ) || $list_lignes[0][132]=='non' )$query .= $db->quote( "non" ).",";
					else if($list_lignes[0][132]=='NO')$query .= $db->quote( "NO" ).",";
					else $query .= $db->quote( $list_lignes[0][133] ).",";
				}
				
				$query .= $db->quote( $list_lignes[0][134] ).",";
				$query .= $db->quote( $list_lignes[0][135] ).",";
				$query .= $db->quote( $list_lignes[0][138] ).",";
				$query .= "0,";
				$query .= $db->quote( $list_lignes[0][140] ).",";
				$query .= "0";

				$query .= ")";
				
			$stmt = $db->prepare($query);
			$stmt->execute();
			
		}
			$db->commit();
			
		} catch (\Exception $e) {
			
			$db->rollback();
			throw $e;
		}
	}

	public function findAll()
	{
		$qb = $this->createQueryBuilder('q');
		$qb->select('q')->addOrderBy( 'substring(q.date,4,2)', 'desc' )
						->addOrderBy( 'substring(q.date,0,2)', 'desc' );
		return $qb->getQuery()->getResult();
	}
}