<?php

namespace AppBundle\Repository;

/**
 * ReferentielPaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReferentielPaRepository extends \Doctrine\ORM\EntityRepository
{
    public function removeBaseReferentiel()
	{
		$db = $this->_em->getConnection();
		$query = "DELETE FROM ref_arret_id";
		$stmt = $db->prepare($query);
		$result = $stmt->execute();
		return $result;
	}

	public function insertDatas( $list_lignes )
	{
		
		$db = $this->_em->getConnection();
		
		try {
				$db->beginTransaction();

				$query = "INSERT INTO ref_arret_id (ligne_id, lig_numero, ligne_libelle, arret_id, point_arret_numero, par_libelle,
										date_importation ) 

				VALUES(";

			
				$query .= $db->quote( $list_lignes[0] ).",";
				$query .= $db->quote( $list_lignes[1] ).",";
				$query .= $db->quote( $list_lignes[2] ).",";
				$query .= $db->quote( $list_lignes[3] ).",";
				$query .= $db->quote( $list_lignes[4] ).",";
				$query .= $db->quote( $list_lignes[5] ).",";
				$query .= $db->quote( date('d/m/Y h:i:s', time()) )."";
			
				$query .= ")";
					
				$stmt = $db->prepare($query);
				$stmt->execute();

			$db->commit();
			
		} catch (\Exception $e) {
			// Rollback the failed transaction attempt
			$db->rollback();
			throw $e;
			//return false;
			//return $e->getCode();
			//return $db->errorCode();
		}
	}
}
