<?php

namespace AppBundle\Repository;

/**
 * ReportingThemeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportingThemeRepository extends \Doctrine\ORM\EntityRepository
{
	public function conforme_by_biv( $table, $field, $value )
	{
		$db = $this->_em->getConnection();
	
		$query = "SELECT COUNT(`$field`) as conforme FROM $table WHERE valid=1 and $field='$value'";
	
		$stmt = $db->prepare($query);
		$stmt->execute();
		$result = $stmt->fetchAll();
	
		return $result;
	}

	
}
