<?php

namespace ClientBundle\Repository;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTickets( $mois_to_show, $year_to_show )
	{
		$db = $this->_em->getConnection();

		$query = "SELECT * FROM ticket WHERE mois='$mois_to_show' AND annee='$year_to_show'";

		$stmt = $db->prepare( $query );
		$stmt->execute();
		
        $result = $stmt->fetchall();

		return $result;
	}

    public function add( $mois, $annee, $enqueteur, $url )
	{
		$db = $this->_em->getConnection();

		$query = "INSERT INTO ticket 
					SET id = DEFAULT,
                        mois=".$db->quote( $mois ).",
						annee=".$db->quote( $annee ).",
						enqueteur=".$db->quote( $enqueteur ).",
						url=".$db->quote( $url );

		$stmt = $db->prepare( $query );
		$stmt->execute();
	}

    public function remove( $id )
	{
		$db = $this->_em->getConnection();

		$query = "DELETE FROM ticket WHERE id=$id";

		$stmt = $db->prepare( $query );
		$stmt->execute();
	}
}
