<?php

namespace BusBundle\Repository;

/**
 * IdPhotosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IdPhotosRepository extends \Doctrine\ORM\EntityRepository
{
    public function listAllByLineDate( $ligne, $date )
	{
		$db = $this->_em->getConnection();
	
		$query = "SELECT * FROM id_photos WHERE ligne='$ligne' AND date='$date' ";

		$stmt = $db->prepare($query);
		$stmt->execute();
		$result = $stmt->fetchAll();
	
		return $result;
	}
}
