<?php

namespace BusBundle\Repository;

/**
 * MesureResetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MesureResetRepository extends \Doctrine\ORM\EntityRepository
{
    public function copyTable( $newTable, $mois )
	{
		$db = $this->_em->getConnection();

        try {
            $db->beginTransaction();
            
            $query = "CREATE TABLE $newTable AS SELECT * FROM questionnaire_s WHERE SUBSTRING(date, 4, 2)='$mois'";
            $stmt = $db->prepare( $query );
            $stmt->execute();

            $query = "DELETE FROM questionnaire_s WHERE SUBSTRING(date, 4, 2)='$mois'";
            $stmt = $db->prepare( $query );
            $stmt->execute();

            $db->commit();
        }
        catch(Exception $e)
        {
            $db->rollBack();
            throw $e;
        }
		
	}
}
