<?php

namespace MobilePaBundle\Repository;

/**
 * EnqueteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnqueteurRepository extends \Doctrine\ORM\EntityRepository
{
    public function login( $login, $pass )
	{
		$db = $this->_em->getConnection();

		$query = "SELECT * FROM enqueteur_mobile WHERE identifiant='$login' AND pass='$pass'";

		$stmt = $db->prepare( $query );
		$stmt->execute();
		$result = $stmt->fetchAll();

		return $result;
	}

    public function get_plannings( $ref_enqueteur, $date_mois )
	{
		$db = $this->_em->getConnection();

		$query = "SELECT * FROM zone_enq WHERE enqueteur='$ref_enqueteur' AND realisee=0
					AND SUBSTRING(date, 4, 2)='$date_mois' ORDER BY date asc";

		$stmt = $db->prepare( $query );
		$stmt->execute();
		$result = $stmt->fetchAll();

		return $result;
	}
}
