<?php

namespace MobilePaBundle\Repository;

/**
 * FeuilleRouteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeuilleRouteRepository extends \Doctrine\ORM\EntityRepository
{
    public function getOne( $mois, $zone )
	{
		$db = $this->_em->getConnection();

		$query = "SELECT * FROM fichier_global WHERE mois='$mois' AND zone='$zone'
                    ORDER BY ordre asc";

		$stmt = $db->prepare( $query );
		$stmt->execute();
		$result = $stmt->fetchAll();

		return $result;
	}
}
